/**
 * @file config.h.cmake
 *
 * @brief Include with configuration of daemon
 *
 * This is file generated by cmake
 *
 */


#cmakedefine ENABLE_REDIS 1
#cmakedefine ENABLE_MYSQL 1
#cmakedefine ENABLE_MEMCACHED 1

#if ENABLE_MYSQL
#include <mysql.h>
void    mysql_conn(void **, jsd_conf *);
typedef MYSQL jsd_mysql;
int     jsd_mysql_info(void **, const char *, char **);
#endif

#if ENABLE_MEMCACHED
#include <libmemcached/memcached.h>
void    memc_conn(void **, jsd_conf *);
typedef memcached_st jsd_memc;
int     jsd_memc_info(void **, const char *, char **);
#endif

#if ENABLE_REDIS
#include <hiredis.h>
void      redis_conn(void **, jsd_conf *);
typedef   redisContext jsd_redis;
int       jsd_redis_info(void **, const char *, char **);
#endif
